#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle	 	true
bspc config focus_follows_pointer	true
bspc config focused_border_color \#689fb7

bspc rule -a firefox:Toolkit state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a firefox state=monocle

killall polybar
polybar example &
#~/.config/polybar/launch.sh --docky

~/.fehbg &
picom --experimental-backends &
dunst &

# touchpad tap-to-click
xinput set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1

# keyboard layout switching
setxkbmap -option grp:alt_shift_toggle &

xmodmap -e "keycode 108 = Super_L"  # reassign Alt_R to Super_L
xmodmap -e "remove mod1 = Super_L"  # make sure X keeps it out of the mod1 group

easyeffects --gapplication-service &

/usr/bin/polkit-dumb-agent

# disable screensaver and DPMS
xset s off -dpms

# use my own session locker
#xidlehook --not-when-audio --timer 600 'xset dpms force off ; betterlockscreen -l blur' '' &
xidlehook --not-when-audio --timer 600 'xset dpms force off' '' &
